[Service]

# change the salt-minion executable with evil-minions
#
# for a full list of commandline switches use `evil-minions --help`
#
ExecStart=
ExecStart=/opt/saltstack/salt/bin/python3.10 /home/user/evil-minions/evil-minions --count=1000 --ramp-up-delay=0 --slowdown-factor=0.0
WorkingDirectory=/home/user/evil-minions

# allow for more generous limits as evil-minion is descriptor-intensive
LimitNOFILE=infinity
TasksMax=infinity

# kill subprocesses when stopping this service
KillMode=control-group
