# This file is a part of Evil Minion.
# Example salt-minion.service overrid file.
# It should be placed in /etc/systemd/system/salt-minion.service.d/.
# DO NOT use evil-minions.service and override.conf together.

[Service]

# change the salt-minion executable with evil-minions
#
# for a full list of commandline switches use `evil-minions --help`
#
ExecStart=
ExecStart=/opt/saltstack/salt/bin/python3.10 /path/to/evil-minions/evil-minions --count=100 --ramp-up-delay=0 --slowdown-factor=0.0 --log-level=INFO
WorkingDirectory=/path/to/evil-minions

# allow for more generous limits as evil-minion is descriptor-intensive
LimitNOFILE=infinity
TasksMax=infinity

# kill subprocesses when stopping this service
KillMode=control-group

# vi: syn=systemd
